homepage/urls.py
# -*- coding: utf-8 -*-
# @Author: ZhuZefeng
# @Date:   2018-11-09 10:42:41
# @Last Modified by:   ZhuZefeng
# @Last Modified time: 2018-11-09 11:12:54


"""
为应用程序lhomepage定义URL模式
"""

from django.urls import path
from .           import views

app_name = 'homepage'

urlpatterns = [
               #网站的主页
               path('',views.homepage, name='homepage'),
              ]

learning_log/urls.py
from django.contrib import admin
from django.urls    import path, include

urlpatterns = [
               path('', include('homepage.urls', namespace='homepage')),
               path('admin/', admin.site.urls),
               path('users/', include('users.urls', namespace='users')),
               path('learning_logs/', include('learning_logs.urls', namespace='learning_logs')),
              ]

learning_logs/urls.py
# -*- coding: utf-8 -*-
# @Author: ZhuZefeng
# @Date:   2018-10-30 17:48:18
# @Last Modified by:   ZhuZefeng
# @Last Modified time: 2018-11-09 11:19:03


"""
为应用程序learning_logs定义URL模式
"""

from django.urls import path, re_path
from .           import views

app_name = 'learning_logs'

urlpatterns = [
               #learning_log的主页
               path('',views.index, name='index'),

               #显示所有主题
               path('topics', views.topics, name='topics'),

               #显示所有题目
               re_path('(?P<topic_name>[A-Z]+)/entries', views.entries, name='entries'),

               #显示所有条目
               re_path('(?P<topic_name>[A-Z]+)/(?P<entry_name>[A-Z]+)/blogs', views.blogs, name='blogs'),

               #用于添加新主题的页面 
               path('new_topic', views.new_topic, name='new_topic'), 

               #用于添加新科目的页面 
               re_path('(?P<topic_name>[A-Z]+)/new_entry', views.new_entry, name='new_entry'),

               #用于添加新条目的页面
               re_path('(?P<topic_name>[A-Z]+)/(?P<entry_name>[A-Z]+)/new_blog', views.new_blog, name='new_blog'),

               #用于编辑条目的页面
               re_path('(?P<topic_name>[A-Z]+)/(?P<entry_name>[A-Z]+)/(?P<blog_name>[A-Z]+)/edit_blog', views.edit_blog, name='edit_blog'),

               #显示当前登录用户创建的所有条目
               re_path('my_blogs', views.my_blogs, name='my_blogs'),

              ]

users/urls.py
# -*- coding: utf-8 -*-
# @Author: ZhuZefeng
# @Date:   2018-11-01 16:59:13
# @Last Modified by:   ZhuZefeng
# @Last Modified time: 2018-11-02 18:09:50


"""为应用程序users定义URL模式"""
from django.contrib.auth.views import LoginView
from django.urls               import path
from .                         import views

app_name = 'users'

urlpatterns = [
               # 登录页面
               path('login/', LoginView.as_view(template_name='users/login.html'), name='login'),

               #注销页面
               path('logout', views.logout_view, name='logout'),

               #注册页面
               path('register', views.register, name='register'),

              ]

homepage/models.py
from django.db import models

# Create your models here.

homepage/views.py
from django.shortcuts import render
from django.urls      import reverse

# Create your views here.
#在此处创建你的视图函数

def homepage(request):
    """网站的主页"""
    return render(request, 'homepage/homepage.html')

homepage/templates/homepage/base.html
{% load bootstrap3 %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>猎户座左旋臂</title>

        {% bootstrap_css %}
        {% bootstrap_javascript %}
    </head>

    <body>   
        <!-- Static navbar -->
        <nav class="navbar navbar-default navbar-static-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button"          class="navbar-toggle collapsed"
                            data-toggle="collapse" data-target="#navbar"
                            aria-expanded="false"  aria-controls="#navbar">                    
                    </button>

                    <a class="navbar-brand" href="{% url 'homepage:homepage' %}">
                        <b>Project Orion</b>
                    </a>
                </div>

                <div id="navbar" class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li>
                            <a href="{% url 'learning_logs:index' %}">学习日志</a>
                        </li>
                        <li>
                            <a href="{% url 'homepage:homepage' %}">财务指标库</a>
                        </li>
                    </ul>

                    <ul class="nav navbar-nav navbar-right">
                        {% if user.is_authenticated %}
                            <li>
                                <a>{{ user.username }}</a>
                            </li>
                            <li>
                                <a href="{% url 'users:logout' %}">注销</a>
                            </li>
                        {% else %}
                            <li>
                                <a href="{% url 'users:register' %}">注册</a>
                            </li>
                            <li>
                                <a href="{% url 'users:login' %}">登录</a>
                            </li>
                        {% endif %}
                    </ul>
                </div>                      
            </div>            
        </nav>

        <div class="container">
            <dir class="page-header">  
                {% block header %}
                {% endblock header %}  
            </dir>
            
            <dir>
                {% block content %}
                {% endblock content %}
            </dir>
        </dir>
    </body>
</html>

homepage/templates/homepage/homepage.html
{% extends "homepage/base.html" %}
{% load bootstrap3 %}

{% block header%}
    <div class='jumbotron'
         onclick="window.open('/learning_logs/','_self')">
        <h2>
            <b>学习日志，追踪您的学习</b>
        </h2>

        <h4>
            <i>
                &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
                --无论您何时开始学习，记得用学习日志来总结您所学到的内容。
            </i>
        </h4>
    </div>
{% endblock header%}