learning_log/urls.py
from django.contrib import admin
from django.urls    import path, include

urlpatterns = [
               path('', include('homepage.urls', namespace='homepage')),
               path('admin/', admin.site.urls),
               path('users/', include('users.urls', namespace='users')),
               path('learning_logs/', include('learning_logs.urls', namespace='learning_logs')),
              ]

learning_logs/urls.py
# -*- coding: utf-8 -*-
# @Author: ZhuZefeng
# @Date:   2018-10-30 17:48:18
# @Last Modified by:   ZhuZefeng
# @Last Modified time: 2018-11-09 11:19:03


"""
为应用程序learning_logs定义URL模式
"""

from django.urls import path, re_path
from .           import views

app_name = 'learning_logs'

urlpatterns = [
               #learning_log的主页
               path('',views.index, name='index'),

               #显示所有主题
               path('topics', views.topics, name='topics'),

               #显示所有题目
               re_path('(?P<topic_name>[A-Z]+)/entries', views.entries, name='entries'),

               #显示所有条目
               re_path('(?P<topic_name>[A-Z]+)/(?P<entry_name>[A-Z]+)/blogs', views.blogs, name='blogs'),

               #用于添加新主题的页面 
               path('new_topic', views.new_topic, name='new_topic'), 

               #用于添加新科目的页面 
               re_path('(?P<topic_name>[A-Z]+)/new_entry', views.new_entry, name='new_entry'),

               #用于添加新条目的页面
               re_path('(?P<topic_name>[A-Z]+)/(?P<entry_name>[A-Z]+)/new_blog', views.new_blog, name='new_blog'),

               #用于编辑条目的页面
               re_path('(?P<topic_name>[A-Z]+)/(?P<entry_name>[A-Z]+)/(?P<blog_name>[A-Z]+)/edit_blog', views.edit_blog, name='edit_blog'),

               #显示当前登录用户创建的所有条目
               re_path('my_blogs', views.my_blogs, name='my_blogs'),

              ]

users/urls.py
# -*- coding: utf-8 -*-
# @Author: ZhuZefeng
# @Date:   2018-11-01 16:59:13
# @Last Modified by:   ZhuZefeng
# @Last Modified time: 2018-11-02 18:09:50


"""为应用程序users定义URL模式"""
from django.contrib.auth.views import LoginView
from django.urls               import path
from .                         import views

app_name = 'users'

urlpatterns = [
               # 登录页面
               path('login/', LoginView.as_view(template_name='users/login.html'), name='login'),

               #注销页面
               path('logout', views.logout_view, name='logout'),

               #注册页面
               path('register', views.register, name='register'),

              ]

learning_logs/models.py
from django.db                  import models
from django.contrib.auth.models import User

# Create your models here.
#在此处创建你的模型。

class Topic(models.Model):
    """用户学习的主题"""
    text       = models.CharField(max_length=20)
    name       = models.CharField(max_length=40)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        """返回模型的字符串表示"""
        return self.text

class Entry(models.Model):
    """用户学习的主题的科目"""
    topic      = models.ForeignKey(Topic, on_delete=models.CASCADE)
    text       = models.CharField(max_length=100)
    name       = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'entries'

    def __str__(self):
        """返回模型的字符串表示"""
        return self.text

class Blog(models.Model):
    """用户学习的主题的科目的条目"""
    entry       = models.ForeignKey(Entry, on_delete=models.CASCADE)
    owner       = models.ForeignKey(User, on_delete=models.CASCADE)
    title       = models.CharField(max_length=100)
    name        = models.CharField(max_length=200)
    text        = models.TextField()
    date_added  = models.DateTimeField(auto_now_add=True)
    date_modify = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

learning_logs/forms.py
# -*- coding: utf-8 -*-
# @Author: ZhuZefeng
# @Date:   2018-10-31 14:21:35
# @Last Modified by:   ZeFeng
# @Last Modified time: 2018-11-05 22:02:27


from django  import forms
from .models import Topic, Entry, Blog

class TopicForm(forms.ModelForm):
    class Meta:
        model  = Topic
        fields = ['text', ]
        labels = {'text':'主题名称',}

class EntryForm(forms.ModelForm):
    class Meta:
        model   = Entry
        fields  = ['text',]
        labels  = {'text':'科目名称',}
        #widgets = {'text': forms.Textarea(attrs={'cols': 50})}

class BlogForm(forms.ModelForm):
    class Meta:
        model   = Blog
        fields  = ['title', 'text']
        labels  = {'title':'条目名称', 'text':'学习内容'}
        widgets = {'text': forms.Textarea(attrs={'cols': 22})}

learning_logs/views.py
from django.shortcuts               import render
from django.http                    import HttpResponseRedirect, Http404
from django.urls                    import reverse
from django.contrib.auth.decorators import login_required
from .models                        import Topic, Entry, Blog
from .forms                         import TopicForm, EntryForm, BlogForm
from xpinyin                        import Pinyin

import datetime

# Create your views here.
#在此处创建你的视图函数

def index(request):
    """Learning_log网站的主页"""
    return render(request, 'learning_logs/index.html')

def topics(request):
    """显示所有的主题"""
    topics  = Topic.objects.order_by('date_added')
    context = {'topics':topics}

    return render(request, 'learning_logs/topics.html', context)

def entries(request, topic_name):
    """显示单个主题及其所有的科目"""
    topic   = Topic.objects.get(name=topic_name)
    entries = topic.entry_set.order_by('date_added')
    context = {'topic':topic,'entries':entries}

    return render(request, 'learning_logs/entries.html', context)

def blogs(request,topic_name, entry_name):
    """显示单个主题下某个科目的所有条目"""
    entry   = Entry.objects.get(name=entry_name)
    topic   = entry.topic
    blogs   = entry.blog_set.order_by('-date_modify')
    context = {'topic':topic, 'entry':entry, 'blogs':blogs}

    return render(request, 'learning_logs/blogs.html', context)

@login_required
def new_topic(request):
    """创建新的主题"""
    pinyin = Pinyin()

    if request.method != 'POST':
        #当操作为非提交数据时，则创建一个新的表单
        form = TopicForm()
    else:
        #当操作为提交数据时，则对数据进行处理
        form = TopicForm(request.POST)
        if form.is_valid():
            new_topic      = form.save(commit=False)
            new_topic.name = pinyin.get_initials(new_topic.text, splitter='')
            new_topic.save()
            return HttpResponseRedirect(reverse('learning_logs:topics'))

    context = {'form':form}

    return render(request, 'learning_logs/new_topic.html', context)

@login_required
def new_entry(request, topic_name):
    """在特定的主题中创建新的科目"""
    pinyin = Pinyin()

    topic = Topic.objects.get(name=topic_name)

    if request.method != 'POST':
        #当操作为非提交数据时，则创建一个新的表单
        form = EntryForm()
    else:
        #当操作为提交数据时，则对数据进行处理
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry       = form.save(commit=False)
            new_entry.topic = topic
            new_entry.name  = pinyin.get_initials(new_entry.text, splitter='')
            new_entry.save()
            return HttpResponseRedirect(reverse('learning_logs:entries', args=[topic.name]))

    context = {'topic':topic, 'form':form}

    return render(request, 'learning_logs/new_entry.html', context)

@login_required
def new_blog(request, topic_name, entry_name):
    """在特定主题中的某个科目下创建新的条目"""
    pinyin = Pinyin()

    topic = Topic.objects.get(name=topic_name)
    entry = Entry.objects.get(name=entry_name)

    if request.method != 'POST':
        #当操作为非提交数据时，则创建一个新的表单
        form = BlogForm()
    else:
        #当操作为提交数据时，则对数据进行处理
        form = BlogForm(data=request.POST)
        if form.is_valid():
            new_blog       = form.save(commit=False)
            new_blog.entry = entry
            new_blog.owner = request.user
            new_blog.name  = pinyin.get_initials(new_blog.title, splitter='')
            new_blog.save()
            return HttpResponseRedirect(reverse('learning_logs:blogs', args=[topic_name, entry_name]))

    context = {'topic':topic,'entry':entry, 'form':form}

    return render(request, 'learning_logs/new_blog.html', context)

@login_required
def edit_blog(request, topic_name, entry_name, blog_name):
    """在编辑特定主题中的某个科目下的某个条目"""
    topic = Topic.objects.get(name=topic_name)
    entry = Entry.objects.get(name=entry_name)
    blog  = Blog.objects.get(name=blog_name)

    if blog.owner != request.user:
        raise Http404

    if request.method != 'POST':
        #当操作为非提交数据时，则创建一个新的表单
        form = BlogForm(instance=blog)
    else:
        #当操作为提交数据时，则对数据进行处理
        form = BlogForm(instance=blog, data=request.POST)
        if form.is_valid():
            edit_blog             = form.save(commit=False)
            edit_blog.date_modify = datetime.datetime.now()
            edit_blog.save()
            return HttpResponseRedirect(reverse('learning_logs:blogs', args=[topic.name, entry.name]))

    context = {'topic':topic,'entry':entry, 'blog':blog,'form':form}

    return render(request, 'learning_logs/edit_blog.html', context)

@login_required
def my_blogs(request):
    """显示当前用户创建的所有条目"""
    blogs = Blog.objects.filter(owner=request.user)

    entries = []
    topics  = []

    test_all = []
    
    for blog in blogs:
        test     = []

        entry = blog.entry
        topic = entry.topic

        test = [blog, entry, topic ]
        test_all.append(test)

    context = {'test_all':test_all}

    return render(request, 'learning_logs/my_blogs.html', context)

learning_logs/templates/learning_logs/base.html
{% load bootstrap3 %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>学习日志</title>

        {% bootstrap_css %}
        {% bootstrap_javascript %}
    </head>

    <body>   
        <!-- Static navbar -->
        <nav class="navbar navbar-default navbar-static-top">
            <div class="container">

                <div class="navbar-header">
                    <button type="button"          class="navbar-toggle collapsed"
                            data-toggle="collapse" data-target="#navbar"
                            aria-expanded="false"  aria-controls="#navbar">                    
                    </button>

                    <a class="navbar-brand" href="{% url 'learning_logs:index' %}">
                        <b>学习日志</b>
                    </a>
                </div>

                <div id="navbar" class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li>
                            <a href="{% url 'learning_logs:topics' %}">主题</a>
                        </li>
                    </ul>

                    <ul class="nav navbar-nav navbar-right">
                        {% if user.is_authenticated %}
                            <li>
                                <a>您好, {{ user.username}}.</a>
                            </li>

                            <li>
                                <a href="{% url 'users:logout' %}">注销</a>
                            </li>

                        {% else %}
                            <li>
                                <a href="{% url 'users:register' %}">注册</a>
                            </li>

                            <li>
                                <a href="{% url 'users:login' %}">登录</a>
                            </li>

                        {% endif %}
                    </ul>
                </div><!-- /.nav-collapse -->                
            </div>            
        </nav>

        <div class="container">
            <dir class="page-header">
                {% block header %}
                {% endblock header %}  
            </dir>
            
            <dir>
                {% block content %}
                {% endblock content %}
            </dir>
        </div><!-- /container --> 
    </body>
</html>

learning_logs/templates/learning_logs/blogs.html
{% extends "learning_logs/base.html" %}
{% load bootstrap3 %}

{% block header %}
    <h3>
        <b>条目:</b>
    </h3>
    <small>
        科目:
        <a href="{% url 'learning_logs:entries' topic.name %}">{{ topic }}</a> - 
        {{ entry }}
        &nbsp&nbsp&nbsp&nbsp&nbsp
        <a href="{% url 'learning_logs:new_blog' topic.name entry.name %}">增加新条目</a>
    </small>
{% endblock header %}

{% block content %}
    {% for blog in blogs %}
        <div class="panel panel-default">
            <div class="panel-heading">
                <h4>
                    <b>{{ blog.title|linebreaks }}</b>              
                </h4>
            </div>

            <div class="panel-body">
                {{ blog.text|linebreaks }}
            </div>

            <div class="panel-footer">
                <small>
                    创建人：{{ blog.owner }}
                    &nbsp&nbsp&nbsp&nbsp&nbsp
                    创建时间：{{ blog.date_added|date:'Y-m-d H:i' }}
                    &nbsp&nbsp&nbsp&nbsp&nbsp                    
                    最后编辑：{{ blog.date_modify|date:'Y-m-d H:i' }}
                    &nbsp&nbsp&nbsp&nbsp&nbsp  
                    <a href="{% url 'learning_logs:edit_blog' topic.name entry.name blog.name %}">编辑条目</a>
                </small>
            </div>
        </div><!-- panel -->
    {% empty %}
        <b>该主题下尚无任何条目。</b>
    {% endfor %}
{% endblock content %}

learning_logs/templates/learning_logs/edit_blog.html
{% extends "learning_logs/base.html" %}
{% load bootstrap3 %}

{% block header %}
    <h4>科目:
        <a href="{% url 'learning_logs:entries' topic.name %}">
           {{ topic }}
        </a> -

        <a href="{% url 'learning_logs:blogs' topic.name entry.name %}">
           {{ entry }}
        </a>
    </h4>

    <h2>
        <b>编辑条目:</b>
    </h2>
{% endblock header %}

{% block content %}
    <form action="{% url 'learning_logs:edit_blog' topic.name entry.name blog.name %}" method='post'>
        {% csrf_token %}
        {% bootstrap_form form %}

        {% buttons %}
            <button name="submit" class="btn btn-primary">保存</button>
        {% endbuttons %}
    </form>
{% endblock content %}

learning_logs/templates/learning_logs/entries.html
{% extends "learning_logs/base.html" %}
{% load bootstrap3 %}

{% block header %}
    <h3>
        <b>科目:</b>
    </h3>
    <small>所属主题： {{ topic }}</small>
{% endblock header %}

{% block content %}
    <ul>
        {% for entry in entries %}
            <li>
                <h4>
                    <a href="{% url 'learning_logs:blogs' topic.name entry.name %}">
                        <b>{{ entry.text|linebreaks }}</b>
                    </a>
                <h4>
                 <small>创建时间：{{ entry.date_added|date:'Y-m-d H:i' }}</small> 
            </li>
        {% empty %}
            <li>
                <b>该话题下尚无任何科目。</b>
            </li>
       {% endfor %}
    </ul>

    <a href="{% url 'learning_logs:new_entry' topic.name %}">
        <small>增加新科目</small>
    </a>
{% endblock content %}

learning_logs/templates/learning_logs/index.html
{% extends "learning_logs/base.html" %}

{% block header%}
    <h2>
        <b>学习日志，追踪您的学习</b>
    </h2>
{% endblock header%}

{% block content %}
    <div >
        <ul>
            <li>
                <H4>无论您何时开始学习，记得用学习日志来总结您所学到的内容。</H4>
            </li>
            <li>
                <H4>
                    <a href="{% url 'users:register' %}">
                        <b>注册一个账号</b>
                    </a>
                    用于管理您自己的学习日志, 同时列出所有您参与的主题。
                </H4>           
            </li>       
        </ul>    
    </div>    
{% endblock content %}

learning_logs/templates/learning_logs/my_blogs.html
{% extends "learning_logs/base.html" %}
{% load bootstrap3 %}

{% block header %}  
    <h3>
        <b>用户 {{ user.username }} 当前创建了如下条目:</b>
    </h3>
{% endblock header %}

{% block content %}
    {% for test in test_all %}
        <div class="panel panel-default">
            <div class="panel-heading">
                <h4>
                    <b>{{ test.0.title|linebreaks }}</b>                        
                </h4>
                <small>所属科目: {{ test.2 }} - {{ test.1 }} </small>  
            </div>

            <div class="panel-body">
                {{ test.0.text|linebreaks }}
            </div>

            <div class="panel-footer">
                <small>
                    创建时间：{{ test.0.date_added|date:'Y-m-d H:i' }}</small>
                    &nbsp&nbsp&nbsp&nbsp&nbsp
                    最后编辑：{{ test.0.date_modify|date:'Y-m-d H:i' }}</small>
                    &nbsp&nbsp&nbsp&nbsp&nbsp
                    <a href="{% url 'learning_logs:edit_blog' test.2.name test.1.name test.0.name %}">编辑条目</a>
            </div>
        </div><!-- panel -->
    {% empty %}
        <b>您尚未创建任何条目。</b>
    {% endfor %}

{% endblock content %}

learning_logs/templates/learning_logs/new_blog.html
{% extends "learning_logs/base.html" %}
{% load bootstrap3 %}

{% block header %}
    <h3>
        <b>增加一个新的学习内容:</b>
    </h3>
    <small>
        所属科目:
        <a href="{% url 'learning_logs:entries' topic.name %}">{{ topic }}</a> -
        <a href="{% url 'learning_logs:blogs' topic.name entry.name %}">{{ entry }}</a>
    </small>
{% endblock header %}

{% block content %}
    <form action="{% url 'learning_logs:new_blog' topic.name entry.name %}" method='post' class="form">
        {% csrf_token %}
        {% bootstrap_form form %}
        
        {% buttons %}
            <button name="submit" class="btn btn-primary">增加</button>
        {% endbuttons %}
    </form>
{% endblock content %}

learning_logs/templates/learning_logs/new_entry.html
{% extends "learning_logs/base.html" %}
{% load bootstrap3 %}

{% block header %}
    <h3>
        <b>增加一个新的科目:</b>
    </h3>
    <small> 所属主题：
        <a href="{% url 'learning_logs:entries' topic.name %}">{{ topic }}</a>
    </samll>
{% endblock header %}

{% block content %}
    <form action="{% url 'learning_logs:new_entry' topic.name %}" method='post'>
        {% csrf_token %}
        {% bootstrap_form form %}
        
        {% buttons %}
            <button name="submit" class="btn btn-primary">增加</button>
        {% endbuttons %}
    </form>
{% endblock content %}

learning_logs/templates/learning_logs/new_topic.html
{% extends "learning_logs/base.html" %}
{% load bootstrap3 %}

{% block header %}
    <h3>
        <b>增加一个新的主题:</b>
    </h3>
{% endblock header %}

{% block content %}
    <form action="{% url 'learning_logs:new_topic' %}" method='post'>
        {% csrf_token %}
        {% bootstrap_form form %}
        
        {% buttons %}
            <button name="submit" class="btn btn-primary">增加</button>
        {% endbuttons %}
    </form>
{% endblock content %}

learning_logs/templates/learning_logs/topics.html
{% extends "learning_logs/base.html" %}
{% load bootstrap3 %}

{% block header %}
    <h3>
        <b>主题：</b>
    </h3>
{% endblock header %}

{% block content %}
    <ul>
        {% for topic in topics %}
            <li>
                <h4>
                    <a href="{% url 'learning_logs:entries' topic.name %}"><b>{{ topic }}</b></a>
                <h4>          
            </li>
        {% empty %}
            <li>
                <b>尚未添加任何主题。</b>
            </li>
       {% endfor %}
    </ul>

    
    <a href="{% url 'learning_logs:new_topic' %}">
        <small>添加主题:</small>
    </a>
   
{% endblock content %}